src/java/bean/BookBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import dao.BookDAO;
import entities.Book;
import java.util.List;

/**
 *
 * @author Trong Tran
 */
public class BookBean {

    private BookDAO bdao = new BookDAO();

    public List<Book> getAllBooks() {
        return bdao.getAllBooks();
    }

    public List<Book> getBookByName(String keyWord) {
        return bdao.getBookByName(keyWord);
    }

    public Book getBookByRelativeProps(String name, String author, boolean status) {
        return bdao.getBookByRelativeProps(name, author, status);
    }

    public Book getBookByID(String bookID) {
        return bdao.getBookByID(bookID);
    }

    public boolean returnBook(String bookId, String historyId) {
        return bdao.returnBook(bookId, historyId);
    }

    public List<Book> searchBook(String keyword) {
        return bdao.searchBook(keyword);
    }

    public boolean addBook(String bookId, String name, String author) {
        return bdao.addBook(bookId, name, author);
    }

    public boolean editBook(String bookId, String name, String author) {
        return bdao.editBook(bookId, name, author);
    }
}

src/java/bean/HistoryBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import dao.HistoryDAO;
import entities.History;
import java.sql.Date;
import java.util.List;

/**
 *
 * @author Trong Tran
 */
public class HistoryBean {
    HistoryDAO hdao = new HistoryDAO();
    
    public List<History> getHistoriesByBookID(String bookID){
        return hdao.getHistoriesByBookID(bookID);
    }
    
    public boolean insertHistory(String staffId, String bookID, Date dateLine) {
        return hdao.insertHistory(staffId, bookID, dateLine);
    }
    
     public int getOutDate(String historyId) {
         return hdao.getOutDate(historyId);
     }
}

src/java/bean/IndemnificationBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bean;

import dao.IndemnificationDAO;
import entities.Indemnification;
import java.util.List;

/**
 *
 * @author Trong Tran
 */
public class IndemnificationBean {

    IndemnificationDAO idao = new IndemnificationDAO();

    public List<Indemnification> getIndems() {
        return idao.getIndems();
    }

    public boolean addFee(String staffId, String bookId, float fee, int outDate) {
        return idao.addFee(staffId, bookId, fee, outDate);
    }
}

src/java/entities/History.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.sql.Date;

/**
 *
 * @author Trong Tran
 */
public class History {
    private int historyid;
    private String staffid;
    private String bookid;
    private String bookname;
    private Date dateborrow;
    private Date deadline;
    private Date datereturn;

    public History(int historyid, String staffid, String bookid,String bookname, Date dateborrow, Date deadline, Date datereturn) {
        this.historyid = historyid;
        this.staffid = staffid;
        this.bookid = bookid;
        this.dateborrow = dateborrow;
        this.deadline = deadline;
        this.datereturn = datereturn;
        this.bookname = bookname;
    }

    public String getBookname() {
        return bookname;
    }

    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    
    public int getHistoryid() {
        return historyid;
    }

    public void setHistoryid(int historyid) {
        this.historyid = historyid;
    }

    public String getStaffid() {
        return staffid;
    }

    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }

    public String getBookid() {
        return bookid;
    }

    public void setBookid(String bookid) {
        this.bookid = bookid;
    }

    public Date getDateborrow() {
        return dateborrow;
    }

    public void setDateborrow(Date dateborrow) {
        this.dateborrow = dateborrow;
    }

    public Date getDeadline() {
        return deadline;
    }

    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    public Date getDatereturn() {
        return datereturn;
    }

    public void setDatereturn(Date datereturn) {
        this.datereturn = datereturn;
    }
}

src/java/entities/Indemnification.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.sql.Date;

/**
 *
 * @author Trong Tran
 */
public class Indemnification {
    private int id;
    private String staffId;
    private String bookId;
    private String bookName;
    private float fee;
    private int outDate;

    public Indemnification(int id, String staffId, String bookId, String bookName, float fee, int outDate) {
        this.id = id;
        this.staffId = staffId;
        this.bookId = bookId;
        this.bookName = bookName;
        this.fee = fee;
        this.outDate = outDate;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

   

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getStaffId() {
        return staffId;
    }

    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    public String getBookId() {
        return bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public float getFee() {
        return fee;
    }

    public void setFee(float fee) {
        this.fee = fee;
    }

    public int getOutDate() {
        return outDate;
    }

    public void setOutDate(int outDate) {
        this.outDate = outDate;
    }
    
    
    
}

src/java/servlet/HistoryServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servlet;

import bean.HistoryBean;
import entities.History;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Trong Tran
 */
public class HistoryServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String bookID = request.getParameter("bookID");
        HistoryBean bean = new HistoryBean();
        List<History> histories = bean.getHistoriesByBookID(bookID);
        if(histories != null){
            request.setAttribute("histories", histories);
            request.getRequestDispatcher("history.jsp").forward(request, response);
        }
        
    }
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/servlet/LoginServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servlet;

import bean.StaffBean;
import dao.StaffDAO;
import entities.Staff;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Properties;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Trong Tran
 */
public class LoginServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String username = request.getParameter("username");
        String password = request.getParameter("password");

        if (username != null && password != null) {
            StaffBean bean = new StaffBean();
            Staff staff = new Staff(username,password,null,false);
            bean.setStaff(staff);
            
            Staff sResult = bean.doLogin();
            if (sResult != null) {
                HttpSession session = request.getSession();
                session.setAttribute("userid", sResult.getStaffID());
                session.setAttribute("name", sResult.getName());
                session.setAttribute("rol", sResult.isRol());
                response.sendRedirect("index.jsp");
            } else {
                request.setAttribute("error", true);
                request.getRequestDispatcher("login.jsp").forward(request, response);
            }
        }
    }

    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

web/addBook.jsp
<%-- 
    Document   : addBook
    Created on : Apr 5, 2018, 12:28:09 AM
    Author     : Trong Tran
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="${language}"/>
<fmt:setBundle basename="i18n.text"/>
<c:if test="${sessionScope.userid == null}">
    <c:redirect url="login.jsp"/>
</c:if>
<!DOCTYPE html>
<html lang="${language}">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    </head>
    <body onload="getBookId()">
        <div class="container">
            <%@include file="master.jsp" %>
            <form action="AddServlet" method="post">
                <div class="form-group">
                    <label style="font-weight: 600;" for="bookId"><fmt:message key="title.book.id"/></label>
                    <input readonly required type="text" name="bookId" class="form-control" id="bookId" placeholder="Book Id">

                </div>
                <div class="form-group">
                    <label style="font-weight: 600;" for="name"><fmt:message key="title.book.name"/></label>
                    <input required type="text" name="name" class="form-control" id="name" placeholder="Book name">
                </div>

                <div class="form-group">
                    <label style="font-weight: 600;" for="author"><fmt:message key="title.book.author"/></label>
                    <input required type="text" name="author" class="form-control" id="author" placeholder="Author">
                </div>

                <button type="submit" class="btn btn-primary"><fmt:message key="page.button.addbook"/></button>
            </form>
        </div>
        <script type="text/javascript">
            function getBookId() {
                var d = new Date();
                var n = d.getTime();
                document.getElementById('bookId').value = 'B'+n;
                
            }
        </script>
    </body>

</html>

web/details.jsp
<%-- 
    Document   : details
    Created on : Apr 2, 2018, 10:07:30 PM
    Author     : Trong Tran
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="${language}"/>
<fmt:setBundle basename="i18n.text"/>
<c:if test="${sessionScope.userid == null}">
    <c:redirect url="login.jsp"/>
</c:if>
<!DOCTYPE html>
<html lang="${language}">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Book Details Page</title>
    </head>
    <body>
        <div class="container">
            <%@include file="master.jsp" %>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.id"/>                            
                            </a>
                        </td>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.name"/>    
                            </a>
                        </td>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.author"/>  
                            </a>
                        </td>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.status"/>  
                            </a>
                        </td>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.amount"/>  
                            </a>
                        </td>
                        <c:if test="${book.status eq true}">
                            <td>
                                <a href="#">
                                    Mượn sách  
                                </a>
                            </td>
                        </c:if>
                        <c:if test="${rol eq true}">
                            <td colspan="2">
                                <a href="#">
                                    Thao tác
                                </a>
                            </td>
                        </c:if>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>${book.bookID}</td>
                        <td>${book.name}</td>
                        <td>${book.author}</td>
                        <c:if test="${book.status eq true}">
                            <td><fmt:message key="infomation.book.statustrue"/></td>
                        </c:if >
                        <c:if test="${book.status ne true}">
                            <td><fmt:message key="infomation.book.statusfalse"/></td>
                        </c:if >
                        <td>1</td>
                        <c:if test="${book.status eq true}">
                            <td><button onclick="showDiv()"><fmt:message key="page.button.borrow"/></button></td>
                        </c:if>
                        <c:if test="${rol eq true}">
                            <td><a href="HistoryServlet?bookID=${book.bookID}"><fmt:message key="page.button.history"/></a></td>
                            <td><a href="SearchServlet?bookID=${book.bookID}&type=edit"><fmt:message key="page.button.edit"/></a></td>
                        </c:if>
                    </tr>
                </tbody>
            </table>
            <div style="display: none; margin-top: 20px;" id="borrowForm">
                <form action="BorrowServlet" method="post">
                    <input hidden name="bookID" value="${book.bookID}"/><br/>

                    <label for="book-name"><fmt:message key="title.book.name"/></label>
                    <input readonly style="width: 35%; height: 20px;" type="text" class="form-control" id="book-name" value="${book.name}"/>
                    <br/>
                    <label for="author"><fmt:message key="title.book.author"/></label>
                    <input readonly style="width: 35%; height: 20px;" type="text" class="form-control" id="author" value="${book.author}"/>                  

                    <input hidden name="dateBorrow" id="dateborrow" type="date"/><br/>

                    <label for="deadLine"><fmt:message key="title.history.duedate"/></label>
                    <input readonly name="deadLine" style="width: 35%; height: 20px;" type="date" class="form-control" id="deadLine"/>                  
                    <br/>
                    <button style="color: #fff;
                            background-color: #007bff;
                            border-color: #007bff;padding: 5px 10px;" type="submit" class="btn"><fmt:message key="page.button.submit"/></button>
                    <br/><br/><i><fmt:message key="page.note.borrow"/></i><br/>
                </form>
            </div>
            <p class="text-center text-muted">
                <a href="index.jsp"><fmt:message key="page.button.home"/></a>
            </p>
        </div>
        <script type="text/javascript">
            var today = new Date();
            function showDiv() {
                document.getElementById("borrowForm").style.display = 'block';
                showToday(today);
                showDeadline(today);
            }
            function showToday(today) {
                var dd = today.getDate();
                var mm = today.getMonth() + 1; //January is 0!

                var yyyy = today.getFullYear();
                if (dd < 10) {
                    dd = '0' + dd;
                }
                if (mm < 10) {
                    mm = '0' + mm;
                }
                var today = yyyy + '-' + mm + '-' + dd;
                document.getElementById("dateborrow").value = today;
            }
            function showDeadline(today) {
                var deadLine = new Date(today);
                deadLine.setDate(deadLine.getDate() + 7);
                var dd = deadLine.getDate();
                var mm = deadLine.getMonth() + 1;
                var yyyy = deadLine.getFullYear();
                if (dd < 10) {
                    dd = '0' + dd;
                }
                if (mm < 10) {
                    mm = '0' + mm;
                }
                var someFormattedDate = yyyy + '-' + mm + '-' + dd;
                console.log(someFormattedDate);
                document.getElementById("deadLine").value = someFormattedDate;
            }
        </script>

    </body>
</html>

web/editBook.jsp
<%-- 
    Document   : editBook
    Created on : Apr 5, 2018, 12:58:18 AM
    Author     : Trong Tran
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="${language}"/>
<fmt:setBundle basename="i18n.text"/>
<c:if test="${sessionScope.userid == null}">
    <c:redirect url="login.jsp"/>
</c:if>
<!DOCTYPE html>
<html lang="${language}">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Edit Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
       
        <div class="container">
            <%@include file="master.jsp" %>
            <form action="AddServlet" method="post">
                <div class="form-group">
                    <label style="font-weight: 600;" for="bookId"> <fmt:message key="title.book.id"/></label>
                    <input required readonly type="text" name="bookId" class="form-control" id="bookId" value="${book.bookID}">

                </div>
                <div class="form-group">
                    <label style="font-weight: 600;" for="name"> <fmt:message key="title.book.name"/></label>
                    <input required type="text" name="name" class="form-control" id="name" value="${book.name}">
                </div>

                <div class="form-group">
                    <label style="font-weight: 600;" for="author"> <fmt:message key="title.book.author"/></label>
                    <input required type="text" name="author" class="form-control" id="author" value="${book.author}">
                </div>

                <button type="submit" class="btn btn-primary"><fmt:message key="page.button.updatebook"/></button>
            </form>
        </div>
    </body>
</html>

web/error.jsp
<%-- 
    Document   : error
    Created on : Apr 5, 2018, 1:08:48 AM
    Author     : Trong Tran
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Error!</h1>
    </body>
</html>

web/history.jsp
<%-- 
    Document   : history
    Created on : Apr 2, 2018, 11:32:55 PM
    Author     : Trong Tran
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="${language}"/>
<fmt:setBundle basename="i18n.text"/>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<c:if test="${sessionScope.userid == null}">
    <c:redirect url="login.jsp"/>
</c:if>
<!DOCTYPE html>
<html lang="${language}">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Book History Page</title>
    </head>
    <body>
        <div class="container">
            <%@include file="master.jsp" %>
            <c:if test="${fn:length(histories) > 0}">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>
                                <a href="#">
                                     <fmt:message key="title.history.id"/>                                         
                                </a>
                            </td>
                            <td>
                                <a href="#">
                                    <fmt:message key="title.history.staffid"/>          
                                </a>
                            </td>
                             <td>
                                <a href="#">
                                    <fmt:message key="title.history.bookname"/>          
                                </a>
                            </td>
                            <td>
                                <a href="#">
                                    <fmt:message key="title.history.indate"/> 
                                </a>
                            </td>
                            <td>
                                <a href="#">
                                    <fmt:message key="title.history.duedate"/> 
                                </a>
                            </td>
                            <td>
                                <a href="#">
                                    <fmt:message key="title.history.outdate"/> 
                                </a>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <c:forEach items="${histories}" var="h">
                            <tr>
                                <td>${h.historyid}</td>
                                <td>${h.staffid}</td>
                                <td>${h.bookname}</td>
                                <td><fmt:formatDate value="${h.dateborrow}" pattern="dd-MM-yyyy"/></td>
                                <td><fmt:formatDate value="${h.deadline}" pattern="dd-MM-yyyy"/></td>
                                <c:if test="${not empty h.datereturn}">
                                    <td><fmt:formatDate value="${h.datereturn}" pattern="dd-MM-yyyy"/></td>
                                </c:if>
                                <c:if test="${empty h.datereturn}">
                                    <td style="color: red;"><fmt:message key="page.lable.returned"/></td>
                                </c:if>
                                <c:if test="${rol eq true and empty h.datereturn}">
                                    <td><a href="ReturnedServlet?historyId=${h.historyid}&bookId=${h.bookid}"><fmt:message key="page.button.returned"/></td>
                                </c:if>
                            </tr>
                        </c:forEach>
                    </tbody>
                </table>
            </c:if>
            <c:if test="${fn:length(histories) <= 0}">
                <h4><fmt:message key="page.note.nohistory"/></h4>
            </c:if>
              <p class="text-center text-muted">
                <a href="index.jsp"><fmt:message key="page.button.home"/></a>
            </p>

        </div>
    </body>
</html>

web/index.jsp
<%-- 
    Document   : index.jsp
    Created on : Apr 2, 2018, 8:31:00 PM
    Author     : Trong Tran
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="${language}"/>
<fmt:setBundle basename="i18n.text"/>
<c:if test="${sessionScope.userid == null}">
    <c:redirect url="login.jsp"/>
</c:if>
<!DOCTYPE html>
<html lang="${language}">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Home Page</title>
    </head>
    <body>
        <div class="container">
            <%@include file="master.jsp" %>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>
                            <a href="#">
                               <fmt:message key="title.book.name"/>                         
                            </a>
                        </td>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.author"/>
                            </a>
                        </td>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.status"/>
                            </a>
                        </td>
                        <td>
                            <a href="#">
                                <fmt:message key="title.book.amount"/>
                            </a>
                        </td>
                    </tr>
                </thead>

                <tbody>
                    <c:if test="${search eq true}">
                        <c:forEach items="${booksSearch}" var="b">
                            <tr>                    
                                <td>${b.name}</td>
                                <td>${b.author}</td>
                                <c:if test="${b.status eq true}">
                                    <td><fmt:message key="infomation.book.statustrue"/></td>
                                </c:if >
                                <c:if test="${b.status ne true}">
                                    <td><fmt:message key="infomation.book.statusfalse"/></td>
                                </c:if >
                                <td>1</td>         
                                <td><a href="ViewBook?type=id&bookID=${b.bookID}"><fmt:message key="page.button.details"/></a></td>
                            </tr>
                        </c:forEach>
                    </c:if>
                    <c:if test="${empty search}">
                        <jsp:useBean id="books" scope="request" class="bean.BookBean"/>
                        <c:if test="${param.type ne 'view'}">
                            <c:forEach items="${books.allBooks}" var="b">
                                <tr>                    
                                    <td>${b.name}</td>
                                    <td>${b.author}</td>
                                    <c:if test="${b.status eq true}">
                                        <td><fmt:message key="infomation.book.statustrue"/></td>
                                    </c:if >
                                    <c:if test="${b.status ne true}">
                                        <td><fmt:message key="infomation.book.statusfalse"/></td>
                                    </c:if >
                                    <td>${b.amount}</td>
                                    <c:if test="${b.amount > 1}">
                                        <td><a href="index.jsp?type=view&name=${b.name}"><fmt:message key="page.button.view"/></a></td>
                                    </c:if>
                                    <c:if test="${b.amount == 1}">
                                        <td><a href="ViewBook?type=props&name=${b.name}&author=${b.author}&status=${b.status}"><fmt:message key="page.button.details"/></a></td>
                                    </c:if>
                                </tr>
                            </c:forEach>
                        </c:if>

                        <c:if test="${param.type eq 'view'}">
                            <c:forEach items="${books.getBookByName(param.name)}" var="b">
                                <tr>                    
                                    <td>${b.name}</td>
                                    <td>${b.author}</td>
                                    <c:if test="${b.status eq true}">
                                        <td><fmt:message key="infomation.book.statustrue"/></td>
                                    </c:if >
                                    <c:if test="${b.status ne true}">
                                        <td><fmt:message key="infomation.book.statusfalse"/></td>
                                    </c:if >
                                    <td>1</td>         
                                    <td><a href="ViewBook?type=id&bookID=${b.bookID}"><fmt:message key="page.button.view"/></a></td>
                                </tr>
                            </c:forEach>
                        </c:if>

                    </c:if>

                </tbody>

            </table>

            <p class="text-center text-muted">
                <a href="index.jsp"><fmt:message key="page.button.home"/></a>
            </p>
        </div>
    </div>
</body>
</html>